
title = "geekiam netlify deployment configuration file"

[build]
publish = "dist"
command = "pnpm run build"

[dev]
framework="nuxt"
command = "pnpm run dev" # Command to start your dev server
port= 3850
publish = "dist" # The path to your static content folder
autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser

[build.environment]
NODE_VERSION = "20.12.0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/manifest.webmanifest"
[headers.values]
Content-Type = "application/manifest+json"

[[headers]]
for = "/assets/*"
[headers.values]
cache-control = '''
        max-age=31536000,
        immutable
        '''
[context.branch-deploy]
command = "pnpm run build"
